#include "matrix.h"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace calcx::linear {
namespace { constexpr double epsilon = 1e-10; void same(const Matrix& a,const Matrix& b){if(a.rows()!=b.rows()||a.columns()!=b.columns())throw std::invalid_argument("Matrix dimensions are incompatible.");} void square(const Matrix& m){if(m.rows()!=m.columns())throw std::invalid_argument("Matrix must be square.");} }
Matrix::Matrix(std::size_t rows,std::size_t columns,double value):rowCount(rows),columnCount(columns),values(rows*columns,value){if(!rows||!columns)throw std::invalid_argument("Matrix dimensions must be positive.");}
double& Matrix::at(std::size_t row,std::size_t column){if(row>=rowCount||column>=columnCount)throw std::out_of_range("Matrix index out of range.");return values[row*columnCount+column];}
double Matrix::at(std::size_t row,std::size_t column)const{if(row>=rowCount||column>=columnCount)throw std::out_of_range("Matrix index out of range.");return values[row*columnCount+column];}
std::size_t Matrix::rows()const noexcept{return rowCount;} std::size_t Matrix::columns()const noexcept{return columnCount;}
Matrix add(const Matrix&a,const Matrix&b){same(a,b);Matrix r(a.rows(),a.columns());for(std::size_t i=0;i<a.rows();++i)for(std::size_t j=0;j<a.columns();++j)r.at(i,j)=a.at(i,j)+b.at(i,j);return r;}
Matrix subtract(const Matrix&a,const Matrix&b){same(a,b);Matrix r(a.rows(),a.columns());for(std::size_t i=0;i<a.rows();++i)for(std::size_t j=0;j<a.columns();++j)r.at(i,j)=a.at(i,j)-b.at(i,j);return r;}
Matrix multiply(const Matrix&a,const Matrix&b){if(a.columns()!=b.rows())throw std::invalid_argument("Matrix dimensions are incompatible for multiplication.");Matrix r(a.rows(),b.columns());for(std::size_t i=0;i<a.rows();++i)for(std::size_t j=0;j<b.columns();++j)for(std::size_t k=0;k<a.columns();++k)r.at(i,j)+=a.at(i,k)*b.at(k,j);return r;}
Matrix transpose(const Matrix&m){Matrix r(m.columns(),m.rows());for(std::size_t i=0;i<m.rows();++i)for(std::size_t j=0;j<m.columns();++j)r.at(j,i)=m.at(i,j);return r;}
Matrix rref(Matrix m){std::size_t pivot=0;for(std::size_t col=0;col<m.columns()&&pivot<m.rows();++col){std::size_t best=pivot;for(std::size_t row=pivot+1;row<m.rows();++row)if(std::abs(m.at(row,col))>std::abs(m.at(best,col)))best=row;if(std::abs(m.at(best,col))<epsilon)continue;for(std::size_t j=0;j<m.columns();++j)std::swap(m.at(best,j),m.at(pivot,j));double divisor=m.at(pivot,col);for(std::size_t j=0;j<m.columns();++j)m.at(pivot,j)/=divisor;for(std::size_t row=0;row<m.rows();++row){if(row==pivot)continue;double factor=m.at(row,col);for(std::size_t j=0;j<m.columns();++j)m.at(row,j)-=factor*m.at(pivot,j);}++pivot;}for(std::size_t i=0;i<m.rows();++i)for(std::size_t j=0;j<m.columns();++j)if(std::abs(m.at(i,j))<epsilon)m.at(i,j)=0;return m;}
double determinant(const Matrix&m){square(m);Matrix a=m;double result=1;int swaps=0;for(std::size_t col=0;col<a.rows();++col){std::size_t best=col;for(std::size_t row=col+1;row<a.rows();++row)if(std::abs(a.at(row,col))>std::abs(a.at(best,col)))best=row;if(std::abs(a.at(best,col))<epsilon)return 0;if(best!=col){for(std::size_t j=0;j<a.columns();++j)std::swap(a.at(best,j),a.at(col,j));++swaps;}result*=a.at(col,col);for(std::size_t row=col+1;row<a.rows();++row){double factor=a.at(row,col)/a.at(col,col);for(std::size_t j=col;j<a.columns();++j)a.at(row,j)-=factor*a.at(col,j);}}return swaps%2?-result:result;}
Matrix inverse(const Matrix&m){square(m);Matrix a(m.rows(),m.columns()*2);for(std::size_t i=0;i<m.rows();++i)for(std::size_t j=0;j<m.columns();++j){a.at(i,j)=m.at(i,j);a.at(i,j+m.columns())=i==j?1:0;}a=rref(a);for(std::size_t i=0;i<m.rows();++i)if(std::abs(a.at(i,i)-1)>epsilon)throw std::invalid_argument("Matrix is singular and cannot be inverted.");Matrix r(m.rows(),m.columns());for(std::size_t i=0;i<m.rows();++i)for(std::size_t j=0;j<m.columns();++j)r.at(i,j)=a.at(i,j+m.columns());return r;}
std::size_t rank(const Matrix&m){Matrix r=rref(m);std::size_t count=0;for(std::size_t i=0;i<r.rows();++i)for(std::size_t j=0;j<r.columns();++j)if(std::abs(r.at(i,j))>=epsilon){++count;break;}return count;}
std::vector<double> solve(const Matrix&a,const std::vector<double>&b){square(a);if(b.size()!=a.rows())throw std::invalid_argument("Linear system dimensions do not match.");Matrix aug(a.rows(),a.columns()+1);for(std::size_t i=0;i<a.rows();++i){for(std::size_t j=0;j<a.columns();++j)aug.at(i,j)=a.at(i,j);aug.at(i,a.columns())=b[i];}Matrix reduced=rref(aug);for(std::size_t i=0;i<reduced.rows();++i){bool zero=true;for(std::size_t j=0;j<a.columns();++j)if(std::abs(reduced.at(i,j))>=epsilon)zero=false;if(zero&&std::abs(reduced.at(i,a.columns()))>=epsilon)throw std::invalid_argument("Linear system has no solution.");}if(rank(a)<a.rows())throw std::invalid_argument("Linear system has infinitely many solutions.");std::vector<double>x(a.rows());for(std::size_t i=0;i<a.rows();++i)x[i]=reduced.at(i,a.columns());return x;}
std::vector<double> eigenvalues2x2(const Matrix&m){square(m);if(m.rows()!=2)throw std::invalid_argument("2x2 matrix required.");double trace=m.at(0,0)+m.at(1,1),disc=trace*trace-4*determinant(m);if(disc< -epsilon)throw std::invalid_argument("Complex eigenvalues are not supported.");double root=std::sqrt(std::max(0.0,disc));return {(trace+root)/2,(trace-root)/2};}
}
