#include "statistics.h"
#include <algorithm>
#include <cmath>
#include <map>
#include <stdexcept>
namespace calcx::statistics {
namespace { constexpr double epsilon=1e-12; std::vector<double> valid(std::vector<double> v){if(v.empty())throw std::invalid_argument("Dataset cannot be empty.");for(double n:v)if(!std::isfinite(n))throw std::invalid_argument("Dataset values must be finite.");return v;} void probs(double a,double b){if(!std::isfinite(a)||a<0||a>1||!std::isfinite(b)||b<0||b>1)throw std::invalid_argument("Probability must be between 0 and 1.");} }
double percentile(std::vector<double> values,double p){auto data=valid(std::move(values));if(!std::isfinite(p)||p<0||p>100)throw std::invalid_argument("Percentile must be between 0 and 100.");std::sort(data.begin(),data.end());double position=(data.size()-1)*p/100.0;auto lower=static_cast<std::size_t>(position);auto upper=static_cast<std::size_t>(std::ceil(position));return data[lower]+(data[upper]-data[lower])*(position-lower);}
Descriptive describe(std::vector<double> values){auto data=valid(std::move(values));Descriptive r{};r.count=data.size();r.sum=0;for(double n:data)r.sum+=n;r.mean=r.sum/r.count;std::sort(data.begin(),data.end());r.minimum=data.front();r.maximum=data.back();r.median=percentile(data,50);r.range=r.maximum-r.minimum;r.q1=percentile(data,25);r.q3=percentile(data,75);r.iqr=r.q3-r.q1;double sumSquares=0;for(double n:data)sumSquares+=(n-r.mean)*(n-r.mean);r.populationVariance=sumSquares/r.count;if(r.count<2)throw std::invalid_argument("Sample variance requires at least 2 observations.");r.sampleVariance=sumSquares/(r.count-1);std::map<double,unsigned> counts;for(double n:data)++counts[n];unsigned maximum=0;for(auto item:counts)maximum=std::max(maximum,item.second);if(maximum>1)for(auto item:counts)if(item.second==maximum)r.modes.push_back(item.first);return r;}
double probability(double favorable,double total){if(!std::isfinite(favorable)||!std::isfinite(total)||favorable<0||total<=0||favorable>total)throw std::invalid_argument("Favorable must be non-negative and no greater than total.");return favorable/total;} double complement(double p){probs(p,p);return 1-p;} double unionProbability(double a,double b,double intersection){probs(a,b);if(!std::isfinite(intersection)||intersection<0||intersection>1)throw std::invalid_argument("Probability must be between 0 and 1.");return a+b-intersection;} double conditionalProbability(double intersection,double given){probs(intersection,given);if(given==0)throw std::invalid_argument("Conditional probability is undefined because P(B) = 0.");return intersection/given;}
double permutations(unsigned n,unsigned r){if(r>n)throw std::invalid_argument("Invalid input: r cannot be greater than n.");double result=1;for(unsigned i=0;i<r;++i){result*=n-i;if(!std::isfinite(result))throw std::overflow_error("Result exceeds supported numeric range.");}return result;} double combinations(unsigned n,unsigned r){if(r>n)throw std::invalid_argument("Invalid input: r cannot be greater than n.");r=std::min(r,n-r);double result=1;for(unsigned i=1;i<=r;++i){result=result*(n-r+i)/i;if(!std::isfinite(result))throw std::overflow_error("Result exceeds supported numeric range.");}return std::round(result);}
double correlation(const std::vector<double>&x,const std::vector<double>&y){if(x.size()!=y.size()||x.size()<2)throw std::invalid_argument("X and Y datasets must contain the same number of values.");double xm=0,ym=0;for(std::size_t i=0;i<x.size();++i){if(!std::isfinite(x[i])||!std::isfinite(y[i]))throw std::invalid_argument("Dataset values must be finite.");xm+=x[i];ym+=y[i];}xm/=x.size();ym/=y.size();double xx=0,yy=0,xy=0;for(std::size_t i=0;i<x.size();++i){xx+=(x[i]-xm)*(x[i]-xm);yy+=(y[i]-ym)*(y[i]-ym);xy+=(x[i]-xm)*(y[i]-ym);}if(xx<epsilon||yy<epsilon)throw std::invalid_argument("Correlation is undefined when either dataset has zero variance.");return std::max(-1.0,std::min(1.0,xy/std::sqrt(xx*yy)));}
Regression regress(const std::vector<double>&x,const std::vector<double>&y){if(x.size()!=y.size()||x.size()<2)throw std::invalid_argument("X and Y datasets must contain the same number of values.");double xm=0,ym=0;for(std::size_t i=0;i<x.size();++i){xm+=x[i];ym+=y[i];}xm/=x.size();ym/=y.size();double xx=0,xy=0;for(std::size_t i=0;i<x.size();++i){xx+=(x[i]-xm)*(x[i]-xm);xy+=(x[i]-xm)*(y[i]-ym);}if(xx<epsilon)throw std::invalid_argument("Linear regression is undefined because X has zero variance.");Regression r{xy/xx,ym-(xy/xx)*xm,correlation(x,y),0,0};r.rSquared=r.r*r.r;for(std::size_t i=0;i<x.size();++i){double residual=y[i]-(r.intercept+r.slope*x[i]);r.sse+=residual*residual;}return r;}
}
