(function () {
  const $ = selector => document.querySelector(selector);
  const result = $("#result");
  const input = $("#expression-input");
  const state = { angle: "deg", base: 10, width: 8 };
  const show = (title, detail, error = false) => { result.classList.toggle("error", error); result.replaceChildren(Object.assign(document.createElement("span"), { className: "result-label", textContent: error ? "CHECK INPUT" : "RESULT" }), Object.assign(document.createElement("strong"), { textContent: title }), Object.assign(document.createElement("span"), { className: "result-detail", textContent: detail })); };
  const format = value => new Intl.NumberFormat("en-US", { maximumFractionDigits: 12 }).format(value);
  const setMode = name => { document.querySelectorAll(".mode-tab").forEach(tab => tab.classList.toggle("active", tab.dataset.mode === name)); document.querySelectorAll(".mode-panel").forEach(panel => { panel.hidden = panel.id !== `${name}-panel`; }); };
  const evaluate = () => { try { show(format(CalcXExpression.evaluate(input.value, state.angle)), "Expression evaluated successfully."); } catch (error) { show(error.message, "Check the expression and try again.", true); } };
  document.querySelectorAll(".mode-tab").forEach(tab => tab.addEventListener("click", () => setMode(tab.dataset.mode)));
  document.querySelectorAll("input[name=angle-mode]").forEach(control => control.addEventListener("change", event => { state.angle = event.target.value; show("Angle mode updated", state.angle === "deg" ? "Trigonometric functions use degrees." : "Trigonometric functions use radians."); }));
  $("#expression-form").addEventListener("submit", event => { event.preventDefault(); evaluate(); });
  $("#expression-clear").addEventListener("click", () => { input.value = ""; show("Ready when you are", "Enter an expression to begin."); input.focus(); });
  document.querySelectorAll("[data-expression]").forEach(button => button.addEventListener("click", () => { input.value = button.dataset.expression; evaluate(); }));
  input.addEventListener("keydown", event => { if (event.key === "Escape") $("#expression-clear").click(); });
  const programmerInput = $("#programmer-input"), programmerOther = $("#programmer-other"), programmerResult = $("#programmer-result");
  const programmerError = message => { programmerResult.classList.add("error"); programmerResult.textContent = message; };
  const renderProgrammer = values => { programmerResult.classList.remove("error"); programmerResult.replaceChildren(Object.assign(document.createElement("strong"), { textContent: `DEC ${values.decimal}` }), Object.assign(document.createElement("span"), { textContent: `BIN ${values.binary}` }), Object.assign(document.createElement("span"), { textContent: `OCT ${values.octal}` }), Object.assign(document.createElement("span"), { textContent: `HEX ${values.hexadecimal}` })); };
  const read = () => CalcXProgrammer.parse(programmerInput.value, state.base);
  const refresh = () => { try { renderProgrammer(CalcXProgrammer.convert(programmerInput.value, state.base, state.width)); } catch (error) { programmerError(error.message); } };
  document.querySelectorAll("[data-base]").forEach(button => button.addEventListener("click", () => { state.base = Number(button.dataset.base); document.querySelectorAll("[data-base]").forEach(item => item.classList.toggle("active", item === button)); refresh(); }));
  document.querySelectorAll("[data-width]").forEach(button => button.addEventListener("click", () => { state.width = Number(button.dataset.width); document.querySelectorAll("[data-width]").forEach(item => item.classList.toggle("active", item === button)); refresh(); }));
  $("#programmer-form").addEventListener("submit", event => { event.preventDefault(); refresh(); });
  document.querySelectorAll("[data-bit-op]").forEach(button => button.addEventListener("click", () => { try { programmerInput.value = CalcXProgrammer.format(CalcXProgrammer.bitwise(read(), CalcXProgrammer.parse(programmerOther.value, state.base), button.dataset.bitOp, state.width), state.base); refresh(); } catch (error) { programmerError(error.message); } }));
  document.querySelectorAll("[data-shift]").forEach(button => button.addEventListener("click", () => { try { programmerInput.value = CalcXProgrammer.format(CalcXProgrammer.shift(read(), Number($("#shift-count").value), button.dataset.shift, state.width), state.base); refresh(); } catch (error) { programmerError(error.message); } }));
  $("#not-button").addEventListener("click", () => { try { programmerInput.value = CalcXProgrammer.format(CalcXProgrammer.not(read(), state.width), state.base); refresh(); } catch (error) { programmerError(error.message); } });
  document.querySelectorAll("[data-bit-action]").forEach(button => button.addEventListener("click", () => { try { programmerInput.value = CalcXProgrammer.format(CalcXProgrammer.manipulate(read(), Number($("#bit-position").value), button.dataset.bitAction, state.width), state.base); refresh(); } catch (error) { programmerError(error.message); } }));
  $("#ascii-button").addEventListener("click", () => { try { const value = programmerInput.value.trim(); programmerResult.classList.remove("error"); programmerResult.textContent = /^\d+$/.test(value) ? `Character ${String.fromCharCode(Number(value))}` : `ASCII ${CalcXProgrammer.ascii(value, "toCode")}`; } catch (error) { programmerError(error.message); } });
  $("#programmer-clear").addEventListener("click", () => { programmerInput.value = "0"; refresh(); });
  setMode("expression"); refresh(); input.focus();
})();
