(function () {
  const $ = selector => document.querySelector(selector);
  const result = $("#result");
  const input = $("#expression-input");
  const state = { angle: "deg", base: 10, width: 8 };
  const show = (title, detail, error = false) => { result.classList.toggle("error", error); result.replaceChildren(Object.assign(document.createElement("span"), { className: "result-label", textContent: error ? "CHECK INPUT" : "RESULT" }), Object.assign(document.createElement("strong"), { textContent: title }), Object.assign(document.createElement("span"), { className: "result-detail", textContent: detail }), Object.assign(document.createElement("div"), { className: "result-actions", innerHTML: '<button id="copy-result" type="button">Copy</button><button id="share-result" type="button">Share</button><button id="export-result" type="button">Export</button>' })); };
  const format = value => new Intl.NumberFormat("en-US", { maximumFractionDigits: 12 }).format(value);
  const setMode = name => { document.querySelectorAll(".mode-tab").forEach(tab => tab.classList.toggle("active", tab.dataset.mode === name)); document.querySelectorAll(".mode-panel").forEach(panel => { panel.hidden = panel.id !== `${name}-panel`; }); };
  const history = JSON.parse(localStorage.getItem("calcx-history") || "[]");
  const recordHistory = (module, action, value) => { history.unshift({ id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now()), timestamp: new Date().toISOString(), module, action, value }); history.splice(50); localStorage.setItem("calcx-history", JSON.stringify(history)); };
  const navigate = name => { if (["expression", "scientific", "programmer", "engineering", "linear-algebra", "statistics"].includes(name)) { setMode(name); $("#dashboard-panel").hidden = true; $("#calculator-workspace").scrollIntoView({ behavior: "smooth", block: "start" }); } else if (name === "dashboard") { $("#dashboard-panel").hidden = false; document.querySelectorAll(".mode-panel").forEach(panel => { panel.hidden = true; }); } else if (name === "history") { showHistory(); } else show("Coming soon", `${name[0].toUpperCase()}${name.slice(1)} is not implemented yet.`); };
  const showHistory = () => { let panel = $("#history-panel"); if (!panel) { panel = document.createElement("section"); panel.id = "history-panel"; panel.className = "overlay-panel"; document.body.append(panel); } panel.innerHTML = `<div class="overlay-heading"><h2>Local History</h2><button id="close-history" type="button">Close</button></div>${history.length ? history.map(item => `<article><time>${new Date(item.timestamp).toLocaleString()}</time><strong>${item.module}</strong><span>${item.action}: ${item.value}</span><button data-copy-history="${item.id}" type="button">Copy</button></article>`).join("") : "<p>No local calculations yet.</p>"}<button id="clear-history" class="reset" type="button">Clear local history</button>`; panel.hidden = false; $("#close-history").onclick = () => { panel.hidden = true; }; $("#clear-history").onclick = () => { history.splice(0); localStorage.removeItem("calcx-history"); panel.hidden = true; }; panel.querySelectorAll("[data-copy-history]").forEach(button => { button.onclick = async () => { const item = history.find(entry => entry.id === button.dataset.copyHistory); await navigator.clipboard?.writeText(`${item.module}\n${item.action}: ${item.value}`); button.textContent = "Copied"; }; }); };
  document.querySelectorAll("[data-nav]").forEach(control => control.addEventListener("click", () => navigate(control.dataset.nav)));
  $("#theme-toggle").addEventListener("click", () => { const light = document.body.classList.toggle("light-theme"); localStorage.setItem("calcx-theme", light ? "light" : "dark"); $("#theme-toggle").textContent = light ? "Dark mode" : "Light mode"; });
  if (localStorage.getItem("calcx-theme") === "light") { document.body.classList.add("light-theme"); $("#theme-toggle").textContent = "Dark mode"; }
  $("#history-toggle").addEventListener("click", showHistory);
  $("#settings-toggle").addEventListener("click", () => show("Settings", "Theme, keyboard, calculation, and local history settings are available from this workspace."));
  document.addEventListener("keydown", event => { const modifier = event.ctrlKey || event.metaKey; if (modifier && event.key.toLowerCase() === "k") { event.preventDefault(); $("#global-search-input").focus(); } if (modifier && event.key.toLowerCase() === "h") { event.preventDefault(); showHistory(); } if (event.key === "Escape") { $("#history-panel")?.setAttribute("hidden", ""); } });
  $("#global-search-input").addEventListener("input", event => { const query = event.target.value.toLowerCase(); document.querySelectorAll("[data-nav]").forEach(control => { control.hidden = query && !control.textContent.toLowerCase().includes(query); }); });
  $("#copy-result").addEventListener("click", async event => { const text = $("#result").innerText; try { await navigator.clipboard.writeText(text); event.target.textContent = "Copied"; } catch { event.target.textContent = "Copy unavailable"; } });
  $("#share-result").addEventListener("click", async () => { const text = $("#result").innerText; if (navigator.share) await navigator.share({ title: "CalcX Result", text }); else await navigator.clipboard?.writeText(text); });
  $("#export-result").addEventListener("click", () => { const blob = new Blob([$("#result").innerText], { type: "text/plain" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `calcx-result-${new Date().toISOString().slice(0, 10)}.txt`; link.click(); URL.revokeObjectURL(link.href); });
  result.addEventListener("click", async event => { if (event.target.id === "copy-result") { try { await navigator.clipboard.writeText(result.innerText); event.target.textContent = "Copied"; } catch { event.target.textContent = "Copy unavailable"; } } if (event.target.id === "share-result") { const text = result.innerText; if (navigator.share) await navigator.share({ title: "CalcX Result", text }); else await navigator.clipboard?.writeText(text); } if (event.target.id === "export-result") { const blob = new Blob([result.innerText], { type: "text/plain" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `calcx-result-${new Date().toISOString().slice(0, 10)}.txt`; link.click(); URL.revokeObjectURL(link.href); } });
  const evaluate = () => { try { const value = format(CalcXExpression.evaluate(input.value, state.angle)); show(value, "Expression evaluated successfully."); recordHistory("Expression", input.value, value); } catch (error) { show(error.message, "Check the expression and try again.", true); } };
  document.querySelectorAll(".mode-tab").forEach(tab => tab.addEventListener("click", () => setMode(tab.dataset.mode)));
  document.querySelectorAll("input[name=angle-mode]").forEach(control => control.addEventListener("change", event => { state.angle = event.target.value; show("Angle mode updated", state.angle === "deg" ? "Trigonometric functions use degrees." : "Trigonometric functions use radians."); }));
  $("#expression-form").addEventListener("submit", event => { event.preventDefault(); evaluate(); });
  $("#expression-clear").addEventListener("click", () => { input.value = ""; show("Ready when you are", "Enter an expression to begin."); input.focus(); });
  document.querySelectorAll("[data-expression]").forEach(button => button.addEventListener("click", () => { input.value = button.dataset.expression; evaluate(); }));
  input.addEventListener("keydown", event => { if (event.key === "Escape") $("#expression-clear").click(); });
  const programmerInput = $("#programmer-input"), programmerOther = $("#programmer-other"), programmerResult = $("#programmer-result");
  const programmerError = message => { programmerResult.classList.add("error"); programmerResult.textContent = message; };
  const renderProgrammer = values => { programmerResult.classList.remove("error"); programmerResult.replaceChildren(Object.assign(document.createElement("strong"), { textContent: `DEC ${values.decimal}` }), Object.assign(document.createElement("span"), { textContent: `BIN ${values.binary}` }), Object.assign(document.createElement("span"), { textContent: `OCT ${values.octal}` }), Object.assign(document.createElement("span"), { textContent: `HEX ${values.hexadecimal}` })); };
  const read = () => CalcXProgrammer.parse(programmerInput.value, state.base);
  const refresh = () => { try { renderProgrammer(CalcXProgrammer.convert(programmerInput.value, state.base, state.width)); } catch (error) { programmerError(error.message); } };
  document.querySelectorAll("[data-base]").forEach(button => button.addEventListener("click", () => { state.base = Number(button.dataset.base); document.querySelectorAll("[data-base]").forEach(item => item.classList.toggle("active", item === button)); refresh(); }));
  document.querySelectorAll("[data-width]").forEach(button => button.addEventListener("click", () => { state.width = Number(button.dataset.width); document.querySelectorAll("[data-width]").forEach(item => item.classList.toggle("active", item === button)); refresh(); }));
  $("#programmer-form").addEventListener("submit", event => { event.preventDefault(); refresh(); });
  document.querySelectorAll("[data-bit-op]").forEach(button => button.addEventListener("click", () => { try { programmerInput.value = CalcXProgrammer.format(CalcXProgrammer.bitwise(read(), CalcXProgrammer.parse(programmerOther.value, state.base), button.dataset.bitOp, state.width), state.base); refresh(); } catch (error) { programmerError(error.message); } }));
  document.querySelectorAll("[data-shift]").forEach(button => button.addEventListener("click", () => { try { programmerInput.value = CalcXProgrammer.format(CalcXProgrammer.shift(read(), Number($("#shift-count").value), button.dataset.shift, state.width), state.base); refresh(); } catch (error) { programmerError(error.message); } }));
  $("#not-button").addEventListener("click", () => { try { programmerInput.value = CalcXProgrammer.format(CalcXProgrammer.not(read(), state.width), state.base); refresh(); } catch (error) { programmerError(error.message); } });
  document.querySelectorAll("[data-bit-action]").forEach(button => button.addEventListener("click", () => { try { programmerInput.value = CalcXProgrammer.format(CalcXProgrammer.manipulate(read(), Number($("#bit-position").value), button.dataset.bitAction, state.width), state.base); refresh(); } catch (error) { programmerError(error.message); } }));
  $("#ascii-button").addEventListener("click", () => { try { const value = programmerInput.value.trim(); programmerResult.classList.remove("error"); programmerResult.textContent = /^\d+$/.test(value) ? `Character ${String.fromCharCode(Number(value))}` : `ASCII ${CalcXProgrammer.ascii(value, "toCode")}`; } catch (error) { programmerError(error.message); } });
  $("#programmer-clear").addEventListener("click", () => { programmerInput.value = "0"; refresh(); });
  const engineeringResult = $("#engineering-result");
  function showEngineering(calculation) {
    const values = calculation.value != null ? `${CalcXEngineering.format(calculation.value, calculation.unit)}` : `I1 = ${CalcXEngineering.format(calculation.value1, calculation.unit)}; I2 = ${CalcXEngineering.format(calculation.value2, calculation.unit)}`;
    engineeringResult.classList.remove("error");
    engineeringResult.innerHTML = `<strong>${values}</strong><span>Formula: ${calculation.formula || "Result"}</span><span>Calculation: ${calculation.calculation || "Completed successfully."}</span>${calculation.warning ? `<span>${calculation.warning}</span>` : ""}`;
  }
  function field(form, name) { return form.elements[name].value; }
  document.querySelectorAll(".engineering-form").forEach(form => form.addEventListener("submit", event => {
    event.preventDefault();
    try {
      const type = form.dataset.engineering;
      let calculation;
      if (type === "ohm") calculation = CalcXEngineering.ohmsLaw(field(form, "unknown"), field(form, "unknown") === "voltage" ? null : field(form, "voltage"), field(form, "unknown") === "current" ? null : field(form, "current"), field(form, "unknown") === "resistance" ? null : field(form, "resistance"));
      if (type === "power") calculation = CalcXEngineering.power("power", field(form, "voltage"), field(form, "current"), null);
      if (type === "network") calculation = { value: field(form, "network") === "series" ? CalcXEngineering.series(field(form, "values").split(",")) : CalcXEngineering.parallel(field(form, "values").split(",")), formula: field(form, "network") === "series" ? "Rtotal = R1 + R2 + ..." : "1/Rtotal = Σ(1/R)", calculation: field(form, "values"), unit: "Ω" };
      if (type === "divider") calculation = field(form, "divider") === "voltage" ? CalcXEngineering.voltageDivider(field(form, "input"), field(form, "r1"), field(form, "r2")) : CalcXEngineering.currentDivider(field(form, "input"), field(form, "r1"), field(form, "r2"));
      if (type === "led") calculation = CalcXEngineering.led(field(form, "supply"), field(form, "forward"), field(form, "current"), Number(field(form, "rating")));
      if (type === "time") calculation = field(form, "timeType") === "rc" ? CalcXEngineering.rc(field(form, "resistance"), field(form, "capacitance")) : CalcXEngineering.rl(field(form, "inductance"), field(form, "resistance"));
      if (type === "waves") calculation = field(form, "waveType") === "frequency" ? CalcXEngineering.frequency("frequency", field(form, "a")) : field(form, "waveType") === "period" ? CalcXEngineering.frequency("period", field(form, "a")) : CalcXEngineering.wavelength("wavelength", field(form, "b"), field(form, "a"));
      if (type === "sampling") calculation = CalcXEngineering.sampling(field(form, "frequency"));
      if (type === "db") calculation = CalcXEngineering.decibels(field(form, "dbType"), field(form, "ratio"));
      showEngineering(calculation);
    } catch (error) { engineeringResult.classList.add("error"); engineeringResult.textContent = error.message; }
  }));
  const quickSearch = $("#quick-search-input"), quickMenu = $("#quick-search-menu"), linearMenu = $("#quick-linear-menu");
  quickSearch.addEventListener("focus", () => { quickMenu.hidden = false; linearMenu.hidden = false; });
  quickSearch.addEventListener("input", () => { const query = quickSearch.value.toLowerCase(); quickMenu.querySelectorAll("button").forEach(button => { button.hidden = query && !button.textContent.toLowerCase().includes(query); }); });
  quickMenu.querySelectorAll("[data-quick]").forEach(button => button.addEventListener("click", () => { setMode("expression"); input.value += button.dataset.quick; input.focus(); quickMenu.hidden = true; }));
  quickMenu.querySelectorAll("[data-quick-mode]").forEach(button => button.addEventListener("click", () => { setMode(button.dataset.quickMode); quickMenu.hidden = true; }));
  linearMenu.querySelectorAll("[data-quick-mode]").forEach(button => button.addEventListener("click", () => { setMode(button.dataset.quickMode); linearMenu.hidden = true; quickMenu.hidden = true; }));
  const matrixResult = $("#matrix-result");
  const parseMatrix = value => value.split(";").map(row => row.split(",").map(Number));
  const matrixText = matrix => matrix.map(row => `[ ${row.map(value => Number(value.toFixed(6))).join("  ")} ]`).join("\n");
  $("#matrix-calculate").addEventListener("click", () => {
    try {
      const operation = $("#matrix-operation").value, a = parseMatrix($("#matrix-a").value), b = parseMatrix($("#matrix-b").value), vector = parseMatrix($("#matrix-vector").value);
      let value, formula = "";
      if (operation === "add") { value = CalcXMatrix.add(a, b); formula = "A + B"; }
      if (operation === "subtract") { value = CalcXMatrix.subtract(a, b); formula = "A - B"; }
      if (operation === "multiply") { value = CalcXMatrix.multiply(a, b); formula = "Cij = Σ Aik Bkj"; }
      if (operation === "transpose") { value = CalcXMatrix.transpose(a); formula = "Aᵀ"; }
      if (operation === "determinant") { value = CalcXMatrix.determinant(a); formula = "det(A)"; }
      if (operation === "inverse") { value = CalcXMatrix.inverse(a); formula = "A⁻¹ by Gauss-Jordan elimination"; }
      if (operation === "rank") { value = CalcXMatrix.rank(a); formula = "rank(A) by row reduction"; }
      if (operation === "echelon" || operation === "rref") { const reduction = CalcXMatrix.echelon(a, operation === "rref"); value = reduction.matrix; formula = `${operation === "rref" ? "RREF" : "Row echelon form"}; Steps: ${reduction.steps.join("; ") || "none"}`; }
      if (operation === "solve") { const solution = CalcXMatrix.solve(a, vector); value = solution.values ? solution.values.map((item, index) => [`x${index + 1}`, item]) : solution.state; formula = "Ax = b by Gauss-Jordan elimination"; }
      if (operation === "eigenvalues") { value = CalcXMatrix.eigen(a); formula = "det(A - λI) = 0"; }
      if (operation === "eigenvectors") { const values = CalcXMatrix.eigen(a); value = CalcXMatrix.eigenvectors(a, values); formula = "(A - λI)v = 0"; }
      const display = Array.isArray(value) && Array.isArray(value[0]) && typeof value[0][0] === "number" ? matrixText(value) : Array.isArray(value) ? value.map(item => Array.isArray(item) ? `${item[0]} = ${item[1]}` : `λ = ${Number(item.toFixed(6))}`).join("\n") : String(value);
      matrixResult.classList.remove("error"); matrixResult.replaceChildren(Object.assign(document.createElement("strong"), { textContent: display }), Object.assign(document.createElement("span"), { textContent: `Formula: ${formula}` }), Object.assign(document.createElement("span"), { textContent: `Dimensions: ${Array.isArray(value) && Array.isArray(value[0]) ? `${value.length} × ${value[0].length}` : "scalar/result"}` }));
    } catch (error) { matrixResult.classList.add("error"); matrixResult.textContent = error.message; }
  });
  $("#matrix-clear").addEventListener("click", () => { $("#matrix-a").value = ""; $("#matrix-b").value = ""; $("#matrix-vector").value = ""; matrixResult.textContent = "Choose a matrix operation."; });
  quickMenu.querySelectorAll("button").forEach(button => { if (/Determinant|Linear Systems|Eigenvalues/.test(button.textContent)) button.addEventListener("click", () => { setMode("linear-algebra"); $("#matrix-operation").value = button.textContent.toLowerCase().replace(" ", ""); quickMenu.hidden = true; }); });
  const stats = { values: [] };
  const statValues = () => CalcXStatistics.dataset($("#stats-dataset").value.split(","));
  const statOutput = (selector, content, error = false) => { const element = $(selector); element.classList.toggle("error", error); element.textContent = content; };
  $("#stats-load").addEventListener("click", () => { try { stats.values = statValues(); const summary = CalcXStatistics.descriptive(stats.values); statOutput("#stats-summary", `${$("#stats-dataset-name").value}: ${summary.count} values | min ${summary.minimum} | max ${summary.maximum} | sum ${summary.sum} | mean ${summary.mean}`); } catch (error) { statOutput("#stats-summary", error.message, true); } });
  $("#stats-clear").addEventListener("click", () => { stats.values = []; $("#stats-dataset").value = ""; statOutput("#stats-summary", "No dataset loaded."); statOutput("#stats-descriptive", ""); });
  $("#stats-describe").addEventListener("click", () => { try { const values = stats.values.length ? stats.values : statValues(); const summary = CalcXStatistics.descriptive(values); const percentile = CalcXStatistics.quantile(values, $("#stats-percentile").value); statOutput("#stats-descriptive", `Count: ${summary.count}\nSum: ${summary.sum}\nMean: ${summary.mean}\nMedian (Q2): ${summary.median}\nMode: ${summary.modes.length ? summary.modes.join(", ") : "No mode"}\nRange: ${summary.range}\nQ1: ${summary.q1}\nQ3: ${summary.q3}\nIQR: ${summary.iqr}\nPercentile: ${percentile}\nPopulation variance: ${summary.populationVariance}\nSample variance: ${summary.sampleVariance}\nPopulation SD: ${summary.populationSD}\nSample SD: ${summary.sampleSD}`); } catch (error) { statOutput("#stats-descriptive", error.message, true); } });
  $("#stats-probability").addEventListener("submit", event => { event.preventDefault(); try { const form = event.target, type = form.elements.type.value, a = form.elements.a.value, b = form.elements.b.value, c = form.elements.c.value; const value = type === "basic" ? CalcXStatistics.probability(a, b).value : type === "complement" ? CalcXStatistics.complement(a) : type === "union" ? CalcXStatistics.union(a, b, c) : CalcXStatistics.conditional(a, b); statOutput("#stats-probability-result", `${type}: ${value} (${value * 100}%)`); } catch (error) { statOutput("#stats-probability-result", error.message, true); } });
  $("#stats-combinatorics").addEventListener("submit", event => { event.preventDefault(); try { const form = event.target; const value = CalcXStatistics.combinatorics(form.elements.n.value, form.elements.r.value, form.elements.type.value === "permutation"); statOutput("#stats-combinatorics-result", `${form.elements.type.value}: ${value}`); } catch (error) { statOutput("#stats-combinatorics-result", error.message, true); } });
  $("#stats-correlation").addEventListener("submit", event => { event.preventDefault(); try { const form = event.target, value = CalcXStatistics.correlation(form.elements.x.value.split(","), form.elements.y.value.split(",")); statOutput("#stats-correlation-result", `Pearson r: ${value}\n${value > 0 ? "Positive" : value < 0 ? "Negative" : "Weak/no linear"} linear association. Correlation does not imply causation.`); } catch (error) { statOutput("#stats-correlation-result", error.message, true); } });
  $("#stats-regression").addEventListener("submit", event => { event.preventDefault(); try { const form = event.target, value = CalcXStatistics.regression(form.elements.x.value.split(","), form.elements.y.value.split(",")); statOutput("#stats-regression-result", `y = ${value.intercept} + ${value.slope}x\nSlope: ${value.slope}\nIntercept: ${value.intercept}\nR²: ${value.r2}\nSSE: ${value.sse}\nPredicted Y: ${value.predict(form.elements.predict.value)}`); } catch (error) { statOutput("#stats-regression-result", error.message, true); } });
  $("#stats-visualize").addEventListener("click", () => { try { const values = stats.values.length ? stats.values : statValues(); const bins = CalcXStatistics.histogram(values); const canvas = $("#stats-histogram"), context = canvas.getContext("2d"); context.clearRect(0, 0, canvas.width, canvas.height); const max = Math.max(...bins.map(bin => bin.frequency), 1); bins.forEach((bin, index) => { const height = bin.frequency / max * 160; context.fillStyle = "#77f0c4"; context.fillRect(index * canvas.width / bins.length + 8, 190 - height, canvas.width / bins.length - 16, height); }); const line = $("#stats-line").getContext("2d"); line.clearRect(0, 0, 480, 220); line.strokeStyle = "#77f0c4"; line.beginPath(); values.forEach((value, index) => { const x = index * 460 / Math.max(1, values.length - 1) + 10, y = 200 - value / Math.max(...values, 1) * 170; index ? line.lineTo(x, y) : line.moveTo(x, y); }); line.stroke(); const xValues = $("#stats-correlation").elements.x.value.split(",").map(Number), yValues = $("#stats-correlation").elements.y.value.split(",").map(Number), scatter = $("#stats-scatter").getContext("2d"); scatter.clearRect(0, 0, 480, 220); const maxX = Math.max(...xValues), minX = Math.min(...xValues), maxY = Math.max(...yValues), minY = Math.min(...yValues); scatter.fillStyle = "#77f0c4"; xValues.forEach((x, index) => scatter.fillRect(10 + (x - minX) / (maxX - minX || 1) * 460, 200 - (yValues[index] - minY) / (maxY - minY || 1) * 170, 6, 6)); statOutput("#stats-visualization-result", `Histogram bins: ${bins.map(bin => `${bin.start}-${bin.end}: ${bin.frequency}`).join(" | ")}\nBox plot: min ${Math.min(...values)}, Q1 ${CalcXStatistics.quantile(values, 25)}, median ${CalcXStatistics.quantile(values, 50)}, Q3 ${CalcXStatistics.quantile(values, 75)}, max ${Math.max(...values)}\nScatter plot: ${xValues.length} points (X horizontal, Y vertical). Line chart: ${values.length} observations.`); } catch (error) { statOutput("#stats-visualization-result", error.message, true); } });
  linearMenu.querySelectorAll("[data-quick-mode]").forEach(button => { if (/Mean|Variance|Probability|Correlation|Regression|Histogram/.test(button.textContent)) button.addEventListener("click", () => { setMode("statistics"); quickMenu.hidden = true; linearMenu.hidden = true; }); });
  setMode("expression"); refresh(); navigate("dashboard"); input.focus();
})();
