(function (global) {
  const prefixes = { p: 1e-12, n: 1e-9, u: 1e-6, "µ": 1e-6, m: 1e-3, "": 1, k: 1e3, M: 1e6, G: 1e9 };
  const units = {
    resistance: { ohm: 1, kohm: 1e3, Mohm: 1e6 }, capacitance: { F: 1, mF: 1e-3, uF: 1e-6, nF: 1e-9, pF: 1e-12 },
    inductance: { H: 1, mH: 1e-3, uH: 1e-6 }, frequency: { Hz: 1, kHz: 1e3, MHz: 1e6, GHz: 1e9 }, time: { s: 1, ms: 1e-3, us: 1e-6, ns: 1e-9 }, voltage: { V: 1 }, current: { A: 1, mA: 1e-3 }, speed: { "m/s": 1 }
  };
  function finite(value, name) { const number = Number(value); if (!Number.isFinite(number)) throw new Error(`${name} must be a finite number.`); return number; }
  function positive(value, name) { const number = finite(value, name); if (number <= 0) throw new Error(`${name} must be greater than zero.`); return number; }
  function nonNegative(value, name) { const number = finite(value, name); if (number < 0) throw new Error(`${name} cannot be negative.`); return number; }
  function convert(value, unit, category) { const number = finite(value, "Value"); if (!units[category] || !units[category][unit]) throw new Error("Unsupported engineering unit."); return number * units[category][unit]; }
  function format(value, unit) { const absolute = Math.abs(value); if (absolute >= 1e9) return `${(value / 1e9).toPrecision(6)} G${unit}`; if (absolute >= 1e6) return `${(value / 1e6).toPrecision(6)} M${unit}`; if (absolute >= 1e3) return `${(value / 1e3).toPrecision(6)} k${unit}`; if (absolute >= 1 || absolute === 0) return `${value.toPrecision(6)} ${unit}`; if (absolute >= 1e-3) return `${(value * 1e3).toPrecision(6)} m${unit}`; if (absolute >= 1e-6) return `${(value * 1e6).toPrecision(6)} µ${unit}`; if (absolute >= 1e-9) return `${(value * 1e9).toPrecision(6)} n${unit}`; return `${(value * 1e12).toPrecision(6)} p${unit}`; }
  function ohmsLaw(unknown, voltage, current, resistance) { const v = voltage == null ? null : nonNegative(voltage, "Voltage"); const i = current == null ? null : positive(current, "Current"); const r = resistance == null ? null : positive(resistance, "Resistance"); if (unknown === "voltage" && i != null && r != null) return { value: i * r, formula: "V = I × R", calculation: `V = ${i} × ${r}`, unit: "V" }; if (unknown === "current" && v != null && r != null) return { value: v / r, formula: "I = V / R", calculation: `I = ${v} / ${r}`, unit: "A" }; if (unknown === "resistance" && v != null && i != null) return { value: v / i, formula: "R = V / I", calculation: `R = ${v} / ${i}`, unit: "Ω" }; throw new Error("Provide the two known Ohm's law values."); }
  function power(unknown, voltage, current, resistance) { const v = voltage == null ? null : nonNegative(voltage, "Voltage"); const i = current == null ? null : positive(current, "Current"); const r = resistance == null ? null : positive(resistance, "Resistance"); if (unknown === "power" && v != null && i != null) return { value: v * i, formula: "P = V × I", calculation: `P = ${v} × ${i}`, unit: "W" }; if (unknown === "current" && v != null && r != null) return { value: v / r, formula: "I = V / R", calculation: `I = ${v} / ${r}`, unit: "A" }; if (unknown === "voltage" && i != null && r != null) return { value: i * r, formula: "V = I × R", calculation: `V = ${i} × ${r}`, unit: "V" }; if (unknown === "resistance" && v != null && i != null) return { value: v / i, formula: "R = V² / P", calculation: `R = ${v}² / ${i}`, unit: "Ω" }; throw new Error("Provide the known power values."); }
  function series(values) { if (!values.length || values.some(v => positive(v, "Resistance") <= 0)) throw new Error("Enter one or more positive resistors."); return values.reduce((a, b) => a + Number(b), 0); }
  function parallel(values) { if (values.length < 2 || values.some(v => positive(v, "Resistance") <= 0)) throw new Error("Enter at least two positive resistors."); return 1 / values.reduce((sum, value) => sum + 1 / Number(value), 0); }
  function voltageDivider(vin, r1, r2) { const voltage = nonNegative(vin, "Input voltage"); const first = positive(r1, "R1"); const second = positive(r2, "R2"); return { value: voltage * second / (first + second), formula: "Vout = Vin × R2 / (R1 + R2)", calculation: `Vout = ${voltage} × ${second} / (${first} + ${second})`, unit: "V" }; }
  function currentDivider(total, r1, r2) { const current = positive(total, "Total current"); const first = positive(r1, "R1"); const second = positive(r2, "R2"); return { value1: current * second / (first + second), value2: current * first / (first + second), formula: "I1 = Itotal × R2 / (R1 + R2); I2 = Itotal × R1 / (R1 + R2)", calculation: `I1 = ${current} × ${second} / (${first} + ${second})`, unit: "A" }; }
  function led(supply, forward, current, rating) { const vs = nonNegative(supply, "Supply voltage"); const vf = nonNegative(forward, "Forward voltage"); const amps = positive(current, "LED current"); if (vf >= vs) throw new Error("Forward voltage must be below supply voltage."); const resistance = (vs - vf) / amps; const powerValue = amps * amps * resistance; return { value: resistance, power: powerValue, rating, formula: "R = (Vs - Vf) / I; P = I²R", calculation: `R = (${vs} - ${vf}) / ${amps}`, unit: "Ω", warning: powerValue >= rating ? "Calculated power meets or exceeds the selected resistor rating." : powerValue >= rating * 0.6 ? "Use a higher-rated resistor for additional margin." : "Calculation only; verify the real circuit before use." }; }
  function rc(resistance, capacitance) { const r = positive(resistance, "Resistance"); const c = positive(capacitance, "Capacitance"); return { value: r * c, formula: "τ = R × C", calculation: `τ = ${r} × ${c}`, unit: "s" }; }
  function rl(inductance, resistance) { const l = positive(inductance, "Inductance"); const r = positive(resistance, "Resistance"); return { value: l / r, formula: "τ = L / R", calculation: `τ = ${l} / ${r}`, unit: "s" }; }
  function frequency(unknown, value) { const number = positive(value, unknown === "frequency" ? "Period" : "Frequency"); return unknown === "frequency" ? { value: 1 / number, formula: "f = 1 / T", calculation: `f = 1 / ${number}`, unit: "Hz" } : { value: 1 / number, formula: "T = 1 / f", calculation: `T = 1 / ${number}`, unit: "s" }; }
  function wavelength(unknown, speed, frequencyValue, wavelengthValue) { if (unknown === "wavelength") { const v = positive(speed, "Wave speed"); const f = positive(frequencyValue, "Frequency"); return { value: v / f, formula: "λ = v / f", calculation: `λ = ${v} / ${f}`, unit: "m" }; } if (unknown === "frequency") { return { value: positive(speed, "Wave speed") / positive(wavelengthValue, "Wavelength"), formula: "f = v / λ", calculation: `f = ${speed} / ${wavelengthValue}`, unit: "Hz" }; } return { value: positive(frequencyValue, "Frequency") * positive(wavelengthValue, "Wavelength"), formula: "v = f × λ", calculation: `v = ${frequencyValue} × ${wavelengthValue}`, unit: "m/s" }; }
  function sampling(maxFrequency) { const value = positive(maxFrequency, "Maximum signal frequency"); return { value: value * 2, period: 1 / (value * 2), formula: "fs ≥ 2 × fmax", calculation: `fs = 2 × ${value}`, unit: "Hz" }; }
  function decibels(type, ratio) { const value = positive(ratio, "Ratio"); const multiplier = type === "power" ? 10 : 20; return { value: multiplier * Math.log10(value), formula: type === "power" ? "dB = 10 log10(P2 / P1)" : "dB = 20 log10(V2 / V1)", calculation: `dB = ${multiplier} log10(${value})`, unit: "dB" }; }
  global.CalcXEngineering = { convert, format, ohmsLaw, power, series, parallel, voltageDivider, currentDivider, led, rc, rl, frequency, wavelength, sampling, decibels, prefixes, units };
})(typeof window === "undefined" ? globalThis : window);
