(function (global) {
  const EPSILON = 1e-10;
  function validate(matrix) { if (!Array.isArray(matrix) || !matrix.length || !matrix[0].length || matrix.some(row => row.length !== matrix[0].length || row.some(value => !Number.isFinite(Number(value))))) throw new Error("Please enter all matrix elements as valid numbers."); return matrix.map(row => row.map(Number)); }
  function sameShape(a, b) { return a.length === b.length && a[0].length === b[0].length; }
  function add(a, b, sign) { a = validate(a); b = validate(b); if (!sameShape(a, b)) throw new Error("Matrix addition/subtraction requires matrices with the same dimensions."); return a.map((row, i) => row.map((value, j) => value + sign * b[i][j])); }
  function multiply(a, b) { a = validate(a); b = validate(b); if (a[0].length !== b.length) throw new Error("Matrix dimensions are incompatible for multiplication."); return a.map(row => b[0].map((_, j) => row.reduce((sum, value, k) => sum + value * b[k][j], 0))); }
  function transpose(a) { a = validate(a); return a[0].map((_, j) => a.map(row => row[j])); }
  function echelon(input, reduced) { const matrix = validate(input).map(row => row.slice()); const steps = []; let pivotRow = 0; for (let col = 0; col < matrix[0].length && pivotRow < matrix.length; col += 1) { let pivot = pivotRow; for (let row = pivotRow + 1; row < matrix.length; row += 1) if (Math.abs(matrix[row][col]) > Math.abs(matrix[pivot][col])) pivot = row; if (Math.abs(matrix[pivot][col]) < EPSILON) continue; if (pivot !== pivotRow) { [matrix[pivot], matrix[pivotRow]] = [matrix[pivotRow], matrix[pivot]]; steps.push(`R${pivot + 1} ↔ R${pivotRow + 1}`); } const divisor = matrix[pivotRow][col]; if (reduced) { matrix[pivotRow] = matrix[pivotRow].map(value => value / divisor); steps.push(`R${pivotRow + 1} → R${pivotRow + 1} / ${divisor}`); } for (let row = 0; row < matrix.length; row += 1) { if (row === pivotRow || (!reduced && row < pivotRow)) continue; const factor = matrix[row][col] / matrix[pivotRow][col]; if (Math.abs(factor) < EPSILON) continue; matrix[row] = matrix[row].map((value, index) => value - factor * matrix[pivotRow][index]); steps.push(`R${row + 1} → R${row + 1} - (${factor})R${pivotRow + 1}`); } pivotRow += 1; } return { matrix: matrix.map(row => row.map(value => Math.abs(value) < EPSILON ? 0 : value)), steps }; }
  function determinant(input) { const matrix = validate(input); if (matrix.length !== matrix[0].length) throw new Error("Determinant requires a square matrix."); let result = 1; let swaps = 0; for (let col = 0; col < matrix.length; col += 1) { let pivot = col; for (let row = col + 1; row < matrix.length; row += 1) if (Math.abs(matrix[row][col]) > Math.abs(matrix[pivot][col])) pivot = row; if (Math.abs(matrix[pivot][col]) < EPSILON) return 0; if (pivot !== col) { [matrix[pivot], matrix[col]] = [matrix[col], matrix[pivot]]; swaps += 1; } result *= matrix[col][col]; for (let row = col + 1; row < matrix.length; row += 1) { const factor = matrix[row][col] / matrix[col][col]; for (let index = col; index < matrix.length; index += 1) matrix[row][index] -= factor * matrix[col][index]; } } return (swaps % 2 ? -1 : 1) * result; }
  function inverse(input) { const matrix = validate(input); if (matrix.length !== matrix[0].length) throw new Error("Inverse requires a square matrix."); const augmented = matrix.map((row, i) => row.concat(row.map((_, j) => i === j ? 1 : 0))); const reduced = echelon(augmented, true).matrix; if (reduced.some((row, i) => Math.abs(row[i] - 1) > EPSILON)) throw new Error("Matrix is singular and cannot be inverted."); return reduced.map(row => row.slice(matrix.length)); }
  function rank(input) { return echelon(input, false).matrix.filter(row => row.some(value => Math.abs(value) >= EPSILON)).length; }
  function solve(a, b) { const matrix = validate(a); const vector = validate(b); if (vector[0].length !== 1 || matrix.length !== matrix[0].length || vector.length !== matrix.length) throw new Error("Linear systems require a square matrix and matching vector."); const reduced = echelon(matrix.map((row, i) => row.concat(vector[i])), true).matrix; const coefficientRank = rank(matrix); const augmentedRank = rank(reduced.map(row => row.slice(0, matrix.length).concat(row.slice(matrix.length)))); const inconsistent = reduced.some(row => row.slice(0, matrix.length).every(value => Math.abs(value) < EPSILON) && Math.abs(row[matrix.length]) >= EPSILON); if (inconsistent) return { state: "No solution." }; if (coefficientRank < matrix.length || augmentedRank < matrix.length) return { state: "Infinitely many solutions." }; return { state: "Unique solution", values: reduced.map(row => row[matrix.length]) }; }
  function eigen(input) { const matrix = validate(input); if (matrix.length !== matrix[0].length || (matrix.length !== 2 && matrix.length !== 3)) throw new Error("Eigenvalues currently support 2x2 and 3x3 square matrices."); if (matrix.length === 2) { const trace = matrix[0][0] + matrix[1][1]; const determinantValue = determinant(matrix); const discriminant = trace * trace - 4 * determinantValue; if (discriminant < -EPSILON) throw new Error("Complex eigenvalues are not supported in this release."); const root = Math.sqrt(Math.max(0, discriminant)); return [ (trace + root) / 2, (trace - root) / 2 ]; } if (matrix.every((row, i) => row.every((value, j) => i === j || Math.abs(value) < EPSILON))) return matrix.map((row, i) => row[i]); throw new Error("3x3 eigenvalues currently require a diagonal matrix."); }
  function eigenvectors(input, values) { const matrix = validate(input); return values.map(value => { if (matrix.length === 2) { const vector = Math.abs(matrix[0][1]) > EPSILON ? [value - matrix[1][1], matrix[0][1]] : [matrix[1][0], value - matrix[0][0]]; const length = Math.hypot(...vector) || 1; return vector.map(item => item / length); } const vector = matrix.map((row, i) => row[i] === value ? 1 : 0); return vector; }); }
  global.CalcXMatrix = { EPSILON, validate, add: (a, b) => add(a, b, 1), subtract: (a, b) => add(a, b, -1), multiply, transpose, echelon, determinant, inverse, rank, solve, eigen, eigenvectors };
})(typeof window === "undefined" ? globalThis : window);
