(function (global) {
  const EPSILON = 1e-12;
  function dataset(values) {
    if (!Array.isArray(values) || !values.length) throw new Error("Dataset cannot be empty.");
    const result = values.map(value => { const number = Number(String(value).trim()); if (String(value).trim() === "" || Number.isNaN(number)) throw new Error("Invalid numeric value."); if (!Number.isFinite(number)) throw new Error("Infinite values are not supported."); return number; });
    return result;
  }
  function sorted(values) { return dataset(values).slice().sort((a, b) => a - b); }
  function quantile(values, p) { const valuesSorted = sorted(values); const probability = Number(p); if (!Number.isFinite(probability) || probability < 0 || probability > 100) throw new Error("Percentile must be between 0 and 100."); const position = (valuesSorted.length - 1) * probability / 100; const lower = Math.floor(position); const upper = Math.ceil(position); return valuesSorted[lower] + (valuesSorted[upper] - valuesSorted[lower]) * (position - lower); }
  function descriptive(values) { const data = dataset(values); const ordered = sorted(data); const count = data.length; const sum = data.reduce((total, value) => total + value, 0); const mean = sum / count; const median = quantile(data, 50); const counts = new Map(); data.forEach(value => counts.set(value, (counts.get(value) || 0) + 1)); const highest = Math.max(...counts.values()); const modes = highest > 1 ? [...counts].filter(([, frequency]) => frequency === highest).map(([value]) => value) : []; const populationVariance = data.reduce((total, value) => total + (value - mean) ** 2, 0) / count; const sampleVariance = count < 2 ? null : data.reduce((total, value) => total + (value - mean) ** 2, 0) / (count - 1); const q1 = quantile(data, 25); const q3 = quantile(data, 75); return { count, sum, minimum: ordered[0], maximum: ordered[ordered.length - 1], mean, median, modes, range: ordered[ordered.length - 1] - ordered[0], q1, q2: median, q3, iqr: q3 - q1, populationVariance, sampleVariance, populationSD: Math.sqrt(populationVariance), sampleSD: sampleVariance === null ? null : Math.sqrt(sampleVariance), sorted: ordered }; }
  function probability(favorable, total) { const good = Number(favorable), whole = Number(total); if (!Number.isFinite(good) || !Number.isFinite(whole) || good < 0 || whole <= 0 || good > whole) throw new Error("Favorable must be non-negative and no greater than a positive total."); return { value: good / whole, percentage: good / whole * 100 }; }
  function complement(value) { const p = Number(value); if (!Number.isFinite(p) || p < 0 || p > 1) throw new Error("Probability must be between 0 and 1."); return 1 - p; }
  function union(a, b, intersection) { const values = [a, b, intersection].map(Number); if (values.some(value => !Number.isFinite(value) || value < 0 || value > 1)) throw new Error("All probabilities must be between 0 and 1."); return values[0] + values[1] - values[2]; }
  function conditional(intersection, given) { const numerator = Number(intersection), denominator = Number(given); if (!Number.isFinite(numerator) || !Number.isFinite(denominator) || numerator < 0 || numerator > 1 || denominator <= 0 || denominator > 1) throw new Error("Conditional probability requires valid probabilities and P(B) greater than zero."); return numerator / denominator; }
  function combinatorics(n, r, permutation) { const total = Number(n), selected = Number(r); if (!Number.isSafeInteger(total) || !Number.isSafeInteger(selected) || total < 0 || selected < 0) throw new Error("n and r must be non-negative integers."); if (selected > total) throw new Error("Invalid input: r cannot be greater than n."); let answer = 1; const limit = permutation ? selected : Math.min(selected, total - selected); for (let i = 1; i <= limit; i += 1) { answer *= (permutation ? total - i + 1 : total - limit + i) / i; if (!Number.isSafeInteger(Math.round(answer)) || !Number.isFinite(answer)) throw new Error("Result exceeds supported numeric range."); } return Math.round(answer); }
  function paired(x, y) { const left = dataset(x), right = dataset(y); if (left.length !== right.length || left.length < 2) throw new Error("X and Y datasets must contain the same number of values."); return [left, right]; }
  function correlation(x, y) { const [left, right] = paired(x, y); const xMean = left.reduce((a, b) => a + b, 0) / left.length, yMean = right.reduce((a, b) => a + b, 0) / right.length; const xx = left.reduce((sum, value) => sum + (value - xMean) ** 2, 0), yy = right.reduce((sum, value) => sum + (value - yMean) ** 2, 0); if (xx < EPSILON || yy < EPSILON) throw new Error("Correlation is undefined when either dataset has zero variance."); const covariance = left.reduce((sum, value, index) => sum + (value - xMean) * (right[index] - yMean), 0); return Math.max(-1, Math.min(1, covariance / Math.sqrt(xx * yy))); }
  function regression(x, y) { const [left, right] = paired(x, y); const xMean = left.reduce((a, b) => a + b, 0) / left.length, yMean = right.reduce((a, b) => a + b, 0) / right.length; const variance = left.reduce((sum, value) => sum + (value - xMean) ** 2, 0); if (variance < EPSILON) throw new Error("Linear regression is undefined because X has zero variance."); const slope = left.reduce((sum, value, index) => sum + (value - xMean) * (right[index] - yMean), 0) / variance, intercept = yMean - slope * xMean; const residuals = left.map((value, index) => { const predicted = intercept + slope * value; return { x: value, actual: right[index], predicted, residual: right[index] - predicted }; }); const sse = residuals.reduce((sum, row) => sum + row.residual ** 2, 0), r = correlation(left, right); return { slope, intercept, r, r2: r ** 2, sse, residualSD: Math.sqrt(sse / Math.max(1, left.length - 2)), residuals, predict: value => intercept + slope * Number(value) }; }
  function histogram(values, bins = 5) { const data = dataset(values), count = Number(bins); if (!Number.isInteger(count) || count < 1) throw new Error("Bin count must be a positive integer."); const minimum = Math.min(...data), maximum = Math.max(...data), width = (maximum - minimum || 1) / count; return Array.from({ length: count }, (_, index) => ({ start: minimum + index * width, end: index === count - 1 ? maximum : minimum + (index + 1) * width, frequency: data.filter(value => index === count - 1 ? value >= minimum + index * width && value <= maximum : value >= minimum + index * width && value < minimum + (index + 1) * width).length })); }
  global.CalcXStatistics = { EPSILON, dataset, descriptive, probability, complement, union, conditional, combinatorics, correlation, regression, histogram, quantile };
})(typeof window === "undefined" ? globalThis : window);
